apiVersion : v1
kind: Service
metadata:
  name: hello-world-nginx
spec:
  type: NodePort
  selector:
    app: hello-world-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001